apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo-chamber.web.fullname" . }}
  labels:
{{ include "echo-chamber.web.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "echo-chamber.web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/app.env-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/app.env-secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "echo-chamber.web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.webImage.repository }}:{{ .Values.webImage.tag }}"
          imagePullPolicy: {{ .Values.webImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /.health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /.health/readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}"
          imagePullPolicy: {{ .Values.appImage.pullPolicy }}
          ports:
            - name: phpfpm
              containerPort: 9000
          readinessProbe:
            tcpSocket:
              port: phpfpm
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONTAINER_ROLE
              value: 'app'
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-app-config
            - secretRef:
                name: {{ .Release.Name }}-app-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
