version: '3.2'
services:

  #
  # APP SERVER
  #
  app:
    build:
      context: .
      dockerfile: tools/docker/app.dev.docker
      args:
        DOCKER_XDEBUG_PORT: ${DOCKER_XDEBUG_PORT:-9000}
        DOCKER_XDEBUG_HEADER: ${DOCKER_XDEBUG_HEADER:-""}
    user: "${DOCKER_PHP_USER_ID:-www-data}:${DOCKER_PHP_GROUP_ID:-www-data}"
    volumes:
      - ./:/var/www/app:cached
    environment:
      CONTAINER_ROLE: 'app'
      MY_NODE_NAME: "localhost (docker-compose)"
      MY_POD_NAME: "app (docker-compose)"
      APP_NAME: 'LOLOL DOCKER COMPOSE'
      APP_ENV: 'local'
      APP_KEY: 'base64:MAY751xyHxHOEIDTNa251S+El2EgTANBxFOrORmYV48='
      APP_DEBUG: 'true'
      DB_HOST: 'mysql'
      DB_USERNAME: 'echochamber'
      DB_PASSWORD: 'abc123'
      DB_DATABASE: 'echochamber'
      REDIS_HOST: 'redis'
      CACHE_DRIVER: 'redis'
      QUEUE_CONNECTION: 'redis'

  #
  # Task Scheduler
  #
  scheduler:
    build:
      context: .
      dockerfile: tools/docker/app.dev.docker
      args:
        DOCKER_XDEBUG_PORT: ${DOCKER_XDEBUG_PORT:-9000}
        DOCKER_XDEBUG_HEADER: ${DOCKER_XDEBUG_HEADER:-""}
    user: "${DOCKER_PHP_USER_ID:-www-data}:${DOCKER_PHP_GROUP_ID:-www-data}"
    volumes:
      - ./:/var/www/app:cached
    environment:
      CONTAINER_ROLE: 'scheduler-background-loop'
      MY_NODE_NAME: "localhost (docker-compose)"
      MY_POD_NAME: "scheduler (docker-compose)"
      APP_NAME: 'LOLOL DOCKER COMPOSE'
      APP_ENV: 'local'
      APP_KEY: 'base64:MAY751xyHxHOEIDTNa251S+El2EgTANBxFOrORmYV48='
      APP_DEBUG: 'true'
      DB_HOST: 'mysql'
      DB_USERNAME: 'echochamber'
      DB_PASSWORD: 'abc123'
      DB_DATABASE: 'echochamber'
      REDIS_HOST: 'redis'
      CACHE_DRIVER: 'redis'
      QUEUE_CONNECTION: 'redis'

  #
  # Q worker
  #
  queue:
    build:
      context: .
      dockerfile: tools/docker/app.dev.docker
      args:
        DOCKER_XDEBUG_PORT: ${DOCKER_XDEBUG_PORT:-9000}
        DOCKER_XDEBUG_HEADER: ${DOCKER_XDEBUG_HEADER:-""}
    user: "${DOCKER_PHP_USER_ID:-www-data}:${DOCKER_PHP_GROUP_ID:-www-data}"
    volumes:
      - ./:/var/www/app:cached
    environment:
      CONTAINER_ROLE: 'queue'
      MY_NODE_NAME: "localhost (docker-compose)"
      MY_POD_NAME: "queue (docker-compose)"
      APP_NAME: 'LOLOL DOCKER COMPOSE'
      APP_ENV: 'local'
      APP_KEY: 'base64:MAY751xyHxHOEIDTNa251S+El2EgTANBxFOrORmYV48='
      APP_DEBUG: 'true'
      DB_HOST: 'mysql'
      DB_USERNAME: 'echochamber'
      DB_PASSWORD: 'abc123'
      DB_DATABASE: 'echochamber'
      REDIS_HOST: 'redis'
      CACHE_DRIVER: 'redis'
      QUEUE_CONNECTION: 'redis'

  #
  # WEB SERVER
  #
  web:
    image: 'gcr.io/generic-website-hosting/echo-chamber-nginx:latest'
    volumes:
      - ./:/var/www/app:cached
      - ./tools/docker/site-dev.nginx:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: voziv.test

  redis:
    image: redis:5-alpine

  mysql:
    image: mysql:8.0.18
    ports:
      - "${DOCKER_MYSQL_PORT:-3306}:3306"
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'abc123'
      MYSQL_DATABASE: 'echochamber'
      MYSQL_USER: 'echochamber'
      MYSQL_PASSWORD: 'abc123'
